# Change these first
owner: codeadjust # Your GitHub organization or username, where this repository lives
repo: services-status # The name of this repository

sites:
  - name: CodeAdjust Website
    url: https://www.codeadjust.com/robots.txt?$GITHUB_RUN_ID
  - name: CodeAdjust Cloud
    url: https://cloud.codeadjust.com/robots.txt?$GITHUB_RUN_ID

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /services-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CodeAdjust Services Status
  introTitle: CodeAdjust Services Status
  introMessage: View CodeAdjust Services Status

assignees:
  - ashish-khokhar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
