# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: CodeAdjust Website
    url: https://www.codeadjust.com/robots.txt
  - name: CodeAdjust Website AU
    url: https://www.codeadjust.com.au/robots.txt
  - name: CodeAdjust Cloud
    url: https://cloud.codeadjust.com/robots.txt

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /services-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CodeAdjust Services Status
  introTitle: CodeAdjust Services Status
  introMessage: View CodeAdjust Services Status
  navbar:
    - title: Services Status
      href: /Services-Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
